# -*- coding: utf-8 -*-
"""NNDL.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1XLU0tArh6JrKF7e1YfskW1eH543tRkvO

exp 2
"""

# -------------------------------
# SLP USING SCIKIT-LEARN
# -------------------------------

import numpy as np
import pandas as pd
from sklearn.datasets import load_iris
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import Perceptron
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report

# 1. Load dataset
iris = load_iris()
X = iris.data
y = iris.target

# 2. Select only two classes (binary)
X = X[y != 2]
y = y[y != 2]

# 3. Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 4. Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 5. Build SLP model
slp = Perceptron(max_iter=1000, eta0=0.01, random_state=42)

# 6. Train model
slp.fit(X_train, y_train)

# 7. Prediction
y_pred = slp.predict(X_test)

# 8. Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

# -------------------------------
# MLP USING SCIKIT-LEARN
# -------------------------------

from sklearn.neural_network import MLPClassifier

# 1. Load full Iris dataset
iris = load_iris()
X = iris.data
y = iris.target

# 2. Train-test split
X_train, X_test, y_train, y_test = train_test_split(
    X, y, test_size=0.2, random_state=42
)

# 3. Feature scaling
scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

# 4. Build MLP model
mlp = MLPClassifier(
    hidden_layer_sizes=(10, 10),  # two hidden layers
    activation='relu',
    solver='adam',
    max_iter=1000,
    random_state=42
)

# 5. Train model
mlp.fit(X_train, y_train)

# 6. Prediction
y_pred = mlp.predict(X_test)

# 7. Evaluation
print("Accuracy:", accuracy_score(y_test, y_pred))
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("Classification Report:\n", classification_report(y_test, y_pred))

"""exp 3"""

import tensorflow as tf
from tensorflow.keras.datasets import mnist
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Flatten
import matplotlib.pyplot as plt
import numpy as np
# You have to explain for the
# Step 1: Load MNIST dataset
(X_train, y_train), (X_test, y_test) = mnist.load_data()

# Step 2: Normalize data
X_train = X_train / 255.0
X_test = X_test / 255.0

# Step 3: Build Neural Network
model = Sequential([
    Flatten(input_shape=(28, 28)),
    Dense(128, activation='relu'),
    Dense(10, activation='softmax')
])

# Step 4: Compile model # Pratiksha Okay then thank you very much okay the pen return with thanks
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
# Meri Taqdeer Ho Gaya Why
# Step 5: Train model
history = model.fit(X_train, y_train, epochs=5, validation_split=0.1)



# Step 6: Evaluate model
test_loss, test_acc = model.evaluate(X_test, y_test)
print("Test Accuracy:", test_acc)

# ---------------- VISUALIZATION ----------------

# Visualization 1: Sample test images with predictions
predictions = model.predict(X_test)

plt.figure(figsize=(8,8))
for i in range(9):
    plt.subplot(3,3,i+1)
    plt.imshow(X_test[i], cmap='gray')
    plt.title(f"Predicted: {np.argmax(predictions[i])}")
    plt.axis('off')
plt.show()

# Visualization 2: Accuracy graph
plt.plot(history.history['accuracy'])
plt.plot(history.history['val_accuracy'])
plt.title("Model Accuracy")
plt.xlabel("Epochs")
plt.ylabel("Accuracy")
plt.legend(["Train", "Validation"])
plt.show()

# Visualization 3: Loss graph
plt.plot(history.history['loss'])
plt.plot(history.history['val_loss'])
plt.title("Model Loss")
plt.xlabel("Epochs")
plt.ylabel("Loss")
plt.legend(["Train", "Validation"])
plt.show()

"""exp 4"""

import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import seaborn as sns

from tensorflow.keras.datasets import cifar10
from tensorflow.keras.utils import to_categorical
from tensorflow.keras.models import Model
from tensorflow.keras.layers import Dense, Flatten, Dropout
from tensorflow.keras.applications import InceptionV3
from tensorflow.keras.optimizers import Adam
from sklearn.metrics import classification_report, confusion_matrix

SEED_VALUE = 42
np.random.seed(SEED_VALUE)
tf.random.set_seed(SEED_VALUE)

(X_train, y_train), (X_test, y_test) = cifar10.load_data()

print(X_train.shape)
print(X_test.shape)

X_train = tf.image.resize(X_train, (75,75)) / 255.0
X_test = tf.image.resize(X_test, (75,75)) / 255.0

y_train = to_categorical(y_train, 10)
y_test = to_categorical(y_test, 10)

base_model = InceptionV3(weights='imagenet',
                         include_top=False,
                         input_shape=(75,75,3))

base_model.trainable = False

x = base_model.output
x = Flatten()(x)
x = Dense(256, activation='relu')(x)
x = Dropout(0.5)(x)
predictions = Dense(10, activation='softmax')(x)

model = Model(inputs=base_model.input, outputs=predictions)

model.compile(optimizer=Adam(learning_rate=0.001),
              loss='categorical_crossentropy',
              metrics=['accuracy'])

loss, accuracy = model.evaluate(X_test, y_test)
print("Test Accuracy:", accuracy)

y_pred = np.argmax(model.predict(X_test), axis=1)
y_true = np.argmax(y_test, axis=1)

cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(8,6))
sns.heatmap(cm, annot=True, fmt='d')
plt.title("Confusion Matrix")
plt.show()

print(classification_report(y_true, y_pred))

class_names = ['airplane','automobile','bird','cat','deer',
               'dog','frog','horse','ship','truck']

plt.figure(figsize=(10,10))

for i in range(9):
    plt.subplot(3,3,i+1)
    plt.imshow(X_test[i])
    plt.axis('off')
    plt.title("Pred: " + class_names[y_pred[i]])

plt.show()

"""exp 5"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import SimpleRNN, Dense

# Sample temperature data
data = np.array([30, 32, 31, 29, 28, 27, 26, 25, 24, 23])

# Prepare dataset
X, y = [], []
for i in range(len(data)-3):
    X.append(data[i:i+3])
    y.append(data[i+3])

X = np.array(X)
y = np.array(y)

# Build RNN model
model = Sequential()
model.add(SimpleRNN(10, activation='relu', input_shape=(3,1)))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mse')

# Train model
model.fit(X, y, epochs=100, verbose=0)

# Predict
pred = model.predict(X)
print("Predicted:", pred)

"""exp 6"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, RepeatVector, TimeDistributed, Dense

# Sample normal data
data = np.random.normal(0, 1, (100, 10, 1))

# Build LSTM Autoencoder
model = Sequential()
model.add(LSTM(16, activation='relu', input_shape=(10,1)))
model.add(RepeatVector(10))
model.add(LSTM(16, activation='relu', return_sequences=True))
model.add(TimeDistributed(Dense(1)))

model.compile(optimizer='adam', loss='mse')

# Train model
model.fit(data, data, epochs=20, batch_size=8, verbose=0)

# Reconstruction
reconstructed = model.predict(data)

# Calculate error
loss = np.mean(np.abs(data - reconstructed), axis=(1,2))

print("Reconstruction Error:", loss)

"""exp 7"""

# Install
!pip install -q opencv-python

# Import
import cv2
from google.colab import files
from google.colab.patches import cv2_imshow

# Load built-in car detection model (Haar Cascade)
!wget -q https://raw.githubusercontent.com/andrewssobral/vehicle_detection_haarcascades/master/cars.xml

car_cascade = cv2.CascadeClassifier('cars.xml')

# Upload image
uploaded = files.upload()

# Read image
img = cv2.imread(list(uploaded.keys())[0])
gray = cv2.cvtColor(img, cv2.COLOR_BGR2GRAY)

# Detect cars
cars = car_cascade.detectMultiScale(gray, 1.1, 1)

# Draw boxes
for (x, y, w, h) in cars:
    cv2.rectangle(img, (x, y), (x+w, y+h), (0,255,0), 2)
    cv2.putText(img, "Car", (x, y-5), 0, 1, (0,255,0), 2)

# Show result
cv2_imshow(img)

"""exp 8"""

import tensorflow as tf
from tensorflow.keras import layers, models

# Load CIFAR-10 dataset
(x_train, y_train), (x_test, y_test) = tf.keras.datasets.cifar10.load_data()

# Normalize data
x_train, x_test = x_train / 255.0, x_test / 255.0

# Build CNN Model
model = models.Sequential([

    layers.Conv2D(32, (3,3), activation='relu', input_shape=(32,32,3)),
    layers.MaxPooling2D((2,2)),

    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D((2,2)),

    layers.Flatten(),

    layers.Dense(64, activation='relu'),
    layers.Dense(10, activation='softmax')
])

# Compile model
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])

# Train model
model.fit(x_train, y_train, epochs=10)

# Evaluate model
model.evaluate(x_test, y_test)

# ============================================================
# EXP 9 - Pneumonia Detection (SIMPLIFIED - NO DATASET ERROR)
# ============================================================

import tensorflow as tf
from tensorflow.keras import layers, models
from tensorflow.keras.datasets import cifar10

# 1. Load Dataset
(X_train, y_train), (X_test, y_test) = cifar10.load_data()

# Convert to binary (just for demo)
y_train = (y_train > 4).astype(int)
y_test = (y_test > 4).astype(int)

# Normalize
X_train = X_train / 255.0
X_test = X_test / 255.0

# 2. Build CNN Model
model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(32,32,3)),
    layers.MaxPooling2D(2,2),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),
    layers.Flatten(),
    layers.Dense(128, activation='relu'),
    layers.Dense(1, activation='sigmoid')
])

# 3. Compile
model.compile(optimizer='adam',
              loss='binary_crossentropy',
              metrics=['accuracy'])

# 4. Train
model.fit(X_train, y_train, epochs=5, validation_data=(X_test, y_test))

# 5. Evaluate
loss, acc = model.evaluate(X_test, y_test)
print("Test Accuracy:", acc)

# ============================================================
# EXP 10 - GAN for Handwritten Digit Generation
# ============================================================

import tensorflow as tf
import numpy as np
import matplotlib.pyplot as plt
from tensorflow.keras import layers

# 1. Load Dataset
(X_train, _), (_, _) = tf.keras.datasets.mnist.load_data()

# Normalize to [-1,1]
X_train = (X_train - 127.5) / 127.5
X_train = X_train.reshape(-1, 28, 28, 1)

# 2. Generator
def build_generator():
    model = tf.keras.Sequential([
        layers.Dense(128, activation='relu', input_dim=100),
        layers.Dense(256, activation='relu'),
        layers.Dense(784, activation='tanh'),
        layers.Reshape((28,28,1))
    ])
    return model

# 3. Discriminator
def build_discriminator():
    model = tf.keras.Sequential([
        layers.Flatten(input_shape=(28,28,1)),
        layers.Dense(256, activation='relu'),
        layers.Dense(1, activation='sigmoid')
    ])
    return model

generator = build_generator()
discriminator = build_discriminator()

# Compile discriminator
discriminator.compile(optimizer='adam',
                      loss='binary_crossentropy',
                      metrics=['accuracy'])

# 4. GAN Model
discriminator.trainable = False
gan_input = layers.Input(shape=(100,))
fake_img = generator(gan_input)
gan_output = discriminator(fake_img)

gan = tf.keras.Model(gan_input, gan_output)
gan.compile(optimizer='adam', loss='binary_crossentropy')

# 5. Training
epochs = 3000
batch_size = 64

for epoch in range(epochs):
    idx = np.random.randint(0, X_train.shape[0], batch_size)
    real_imgs = X_train[idx]

    noise = np.random.normal(0,1,(batch_size,100))
    fake_imgs = generator.predict(noise, verbose=0)

    discriminator.train_on_batch(real_imgs, np.ones((batch_size,1)))
    discriminator.train_on_batch(fake_imgs, np.zeros((batch_size,1)))

    noise = np.random.normal(0,1,(batch_size,100))
    gan.train_on_batch(noise, np.ones((batch_size,1)))

    if epoch % 1000 == 0:
        print("Epoch:", epoch)

# 6. Generate Images
noise = np.random.normal(0,1,(5,100))
gen_imgs = generator.predict(noise)

plt.figure(figsize=(10,2))
for i in range(5):
    plt.subplot(1,5,i+1)
    plt.imshow(gen_imgs[i].reshape(28,28), cmap='gray')
    plt.axis('off')

plt.show()

# ============================================================
# END
# ============================================================

"""exp 11"""

# Install
!pip install -q opencv-python

# Import
import cv2
from google.colab import files
from google.colab.patches import cv2_imshow

# Upload image
uploaded = files.upload()

# Read image
img = cv2.imread(list(uploaded.keys())[0])

# Load HOG + SVM person detector
hog = cv2.HOGDescriptor()
hog.setSVMDetector(cv2.HOGDescriptor_getDefaultPeopleDetector())

# Detect persons
boxes, weights = hog.detectMultiScale(img, winStride=(8,8))

# Draw bounding boxes
for (x, y, w, h) in boxes:
    cv2.rectangle(img, (x, y), (x+w, y+h), (0,255,0), 2)
    cv2.putText(img, "Person", (x, y-5),
                cv2.FONT_HERSHEY_SIMPLEX, 0.7, (0,255,0), 2)

# Show output
cv2_imshow(img)

"""exp 12"""

import numpy as np
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import LSTM, Dense
from sklearn.metrics import mean_absolute_error, mean_squared_error

data = np.arange(100)

X, y = [], []
for i in range(len(data)-3):
    X.append(data[i:i+3])
    y.append(data[i+3])

X, y = np.array(X), np.array(y)

model = Sequential()
model.add(LSTM(10, input_shape=(3,1)))
model.add(Dense(1))

model.compile(optimizer='adam', loss='mse')
model.fit(X, y, epochs=10, verbose=0)

pred = model.predict(X)

print("MAE:", mean_absolute_error(y, pred))
print("RMSE:", np.sqrt(mean_squared_error(y, pred)))

"""exp 13"""

import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, LSTM, Dense
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences
import numpy as np # Explicitly import numpy

texts = ["good", "bad", "toxic", "nice"]
labels = [0,1,1,0]

tokenizer = Tokenizer()
tokenizer.fit_on_texts(texts)

sequences = tokenizer.texts_to_sequences(texts)
X = pad_sequences(sequences)

# Explicitly convert X and labels to tf.constant to ensure proper data type handling
X = tf.constant(X)
labels = tf.constant(labels)

# Get vocabulary size for clarity in Embedding layer
vocab_size = len(tokenizer.word_index) + 1 # +1 for padding token

model = Sequential()
# Removed 'input_length' as it is deprecated and can be inferred by Keras
model.add(Embedding(input_dim=vocab_size, output_dim=8))
model.add(LSTM(8))
model.add(Dense(1, activation='sigmoid'))

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])
model.fit(X, labels, epochs=5, verbose=1)

"""exp 14"""

# Install transformers
!pip install -q transformers

from transformers import pipeline

# Load model
classifier = pipeline("text-classification")

# Test emails
emails = [
    "I need help with my order",
    "Congratulations! You won a prize",
    "Your account has been updated"
]

# Predict
for mail in emails:
    result = classifier(mail)
    print(mail, "->", result)

"""exp 15"""

from google.colab import files
uploaded = files.upload()

"""To prepare your dataset for `ImageDataGenerator.flow_from_directory()`, you need to organize your images into a main directory (e.g., `dataset`) with subdirectories, where each subdirectory represents a class. For example:

```
/content/dataset/
  class_a/
    image1.jpg
    image2.png
  class_b/
    image3.jpg
    image4.png
```

The following code snippet demonstrates how to create this structure. You'll need to modify the `image_files` list and the `class_mapping` dictionary to reflect your actual image filenames, their current locations, and the classes they belong to.
"""

# Install
!pip install -q tensorflow

from tensorflow.keras.preprocessing.image import ImageDataGenerator
from tensorflow.keras import layers, models

# Data augmentation
train_datagen = ImageDataGenerator(
    rescale=1./255,
    rotation_range=20,
    zoom_range=0.2,
    horizontal_flip=True
)

# Load dataset (folder structure required)
train_data = train_datagen.flow_from_directory(
    '/content/dataset',   # Fixed: Pointing to the newly created dataset folder
    target_size=(128,128),
    batch_size=16,
    class_mode='categorical'
)

# Build CNN model
model = models.Sequential([
    layers.Conv2D(32, (3,3), activation='relu', input_shape=(128,128,3)),
    layers.MaxPooling2D(2,2),
    layers.Conv2D(64, (3,3), activation='relu'),
    layers.MaxPooling2D(2,2),
    layers.Flatten(),
    layers.Dense(64, activation='relu'),
    layers.Dense(train_data.num_classes, activation='softmax')
])

# Compile
model.compile(optimizer='adam', loss='categorical_crossentropy', metrics=['accuracy'])

# Train
model.fit(train_data, epochs=3)

print("Training Completed ")